# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 20:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0068_auto_20171229_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='access_code',
            field=models.CharField(blank=True, help_text='An optional code to prompt contestants before they are allowed to join the contest. Leave it blank to disable.', max_length=255, verbose_name='access code'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='key',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(b'^[a-zA-Z0-9]+$', 'Contest id must be ^[a-z0-9]+$')], verbose_name='contest id'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='time_limit',
            field=models.DurationField(blank=True, help_text='User must solve problems within the time given. Leave it blank to disable.', null=True, verbose_name='time limit'),
        ),
        migrations.AlterField(
            model_name='contestproblem',
            name='points',
            field=models.IntegerField(default=100, verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='code',
            field=models.CharField(help_text='You can only use lower case and hyphen. e.g. pr0b1em-c0de', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(b'^[a-zA-Z0-9\\-]+$', 'Problem code must be ^[a-z0-9]+$')], verbose_name='problem code'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=131072, help_text='The memory limit for this problem, in kilobytes (e.g. 64mb = 65536 kilobytes).', verbose_name='memory limit'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='points',
            field=models.FloatField(default=10.0, help_text='Problem points should be between 1.0 and 20.0', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(20.0)], verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.FloatField(default=1.0, help_text='The time limit for this problem, in seconds. Fractional seconds (e.g. 1.5) are supported.', verbose_name='time limit'),
        ),
    ]
