# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0069_auto_20180120_2033'),
        ('judge', '0069_auto_20180124_2023'),
    ]

    operations = [
    ]
