# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-01 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0071_auto_20180130_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='posted time')),
                ('style', models.CharField(blank=True, max_length=512, verbose_name='class for notification')),
                ('body', models.TextField(max_length=8192, verbose_name='body of notification')),
                ('read', models.BooleanField(default=False, verbose_name='whether user have read')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Profile', verbose_name='commenter')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
            },
        ),
    ]
