# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-02 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0072_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'permissions': (('see_all_notifications', 'See all notifications'), ('send_notification', 'Send notification')), 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False, verbose_name='have read'),
        ),
    ]
