# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-19 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0073_auto_20180502_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='use_balloons',
            field=models.BooleanField(default=False, help_text='If enbaled, use ranking table with balloons', verbose_name='use_balloons'),
        ),
    ]
