# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-22 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0075_auto_20180520_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='short_circuit',
            field=models.BooleanField(default=False, verbose_name='Short circuit'),
        ),
    ]
