# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-30 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0084_contest_formats'),
        ('judge', '0075_auto_20180520_0114'),
    ]

    operations = [
    ]
